name: build-and-push-image
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1-7 * 4' # https://crontab.guru/#0_0_1-7_*_4

jobs:
  build:
    name: "Build and publish"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: docker/setup-buildx-action@v2.0.0

      - name: "Log in into Docker Hub"
        id: "login-docker-hub"
        uses: "docker/login-action@v1"
        with:
          registry: "docker.io"
          username: "${{ secrets.ETEU_DOCKER_HUB_USER }}"
          password: "${{ secrets.ETEU_DOCKER_HUB_SECRET_TOKEN }}"

      - name: "Build and push the image"
        env:
          DOCKER_REGISTRY: "${{ steps.login-ecr.outputs.registry }}"
          DOCKER_REPOSITORY: "eteu/pdfgen"
          IMAGE_COMMIT_TAG: "commit-${{ github.sha }}"
        run: |
          echo "Available platforms: ${{ steps.buildx.outputs.platforms }}"
          exec ./docker/ci.sh

# vim:ft=yaml:et:sw=2:sts=2
